### ISSUE TITLE
Werte runden?

### ISSUE THREAD

**Issue by SabineTobi** [foxthefox/ioBroker.statistics#14]
Beim Berechnen der Werte gibt es da noch ein paar "Ungenauigkeiten":

Von meiner Wetterstation bekomme ich z.B. die Regenmenge als Zahl mit 1 Kommastelle in 0.3er Schritten, die ich als "Zähler im Delta-Verbrauch" verarbeiten lasse.

Im temp Zweig bei den Objects wird dann aber aus 0.3 z.B. beim day Wert 0.2999999999999545 daraus.
Und im save Zweig hab ich da jetzt z.B. aktuell 33.900000000000006 stehen.

Würde es nicht Sinn machen, die Anzahl der Nachkommastellen zu begrenzen (evtl. einstellbar) und die Werte entsprechend zu runden?

**Comment by foxthefox** [comment]
Für die Rundung kann ich was machen, sollte beim nächsten Update machbar sein

**Comment by foxthefox** [comment]
werte sind jetzt ab Version 0.2.1 gerundet

**Comment by Thisoft** [comment]
Kann es sein, dass die Werte jetzt generell auf ganze Zahlen gerundet werden? Oder finde ich nur die Einstellung der Nachkommastellen nicht...?
