### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by misanorot** [foxthefox/ioBroker.statistics#15]
`

statistics.0 | 2019-02-14 21:48:23.415 | error | : message handler implemented, but messagebox not enabled. Define common.messagebox in io-package.json for adapter or delete message handler.
-- | -- | -- | --

`

**Comment by vr6syncro** [comment]
up. getting the same

**Comment by andre1974** [comment]
Me too

**Comment by liv-in-sky** [comment]
me too

**Comment by R-Guhr** [comment]
me too

**Comment by foxthefox** [comment]
deleted it in code
