### ISSUE TITLE
strange values for on per day ...

### ISSUE THREAD

**Issue by Diginix** [foxthefox/ioBroker.statistics#16]
On some devices (e.g. Tasmota, Yeelight) I get values for "on per day" with more than 1 mio seconds.
(1918353 sec and 1651622 sec).

![strange_on-time](https://user-images.githubusercontent.com/39678667/53203857-8b978480-362a-11e9-9c86-473dd80275f6.jpg)

**Comment by foxthefox** [comment]
There is defenitely a factor 1000 too much, so it is milliseconds, I will fix it in next version

**Comment by foxthefox** [comment]
is part of 0.2.1
