### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by GermanBluefox** [foxthefox/ioBroker.statistics#2]
I refactored a bit your very clever adapter: https://github.com/GermanBluefox/ioBroker.statistics/commits?author=GermanBluefox

And wanted before the pull request to discuss some details.

Do you have telegram? Write me you nick info at iobroker.net

**Comment by foxthefox** [comment]
I dont have telegram.
But my nickname in the forum is foxthefox, you can drop me a private message there.

**Comment by foxthefox** [comment]
I merged it and will continue, questions will come in telegram

**Comment by GermanBluefox** [comment]
Thank you:)

Am Sa., 24. Nov. 2018, 17:14 hat foxthefox <notifications@github.com>
geschrieben:
