### ISSUE TITLE
00:00 Uhr DayMin Wert

### ISSUE THREAD

**Issue by LosPimpos** [foxthefox/ioBroker.statistics#22]
Hallo,

für die Avg Werte wird um 0Uhr immer bei DayMin 0 eingetragen. Bei mir z.B. 0°C, 0% Luftfeuchte, obwohl diese Werte nicht real sind. Scheint immer beim Tageswechsel zu passieren. Kann man das anpassen?

**Comment by foxthefox** [comment]
Welche Version ist denn installiert? 
Die derzeitig auf github liegende, ist eine Arbeitsversion und es könnte mit dem Wunsch nach Rundung zusammenhängen.

**Comment by LosPimpos** [comment]
starting. Version 0.2.1 in /opt/iobroker/node_modules/iobroker.statistics, node: v11.10.0

**Comment by holger05** [comment]
Kann ich bestätigen. Mit der 0.2.1. werden die min Werte auf 0 gesetzt. 
Auch bei neu angelegten Werten. Tippe mal, dass der Wert mit 0 initialisiert wird, und dann da neue Werte > 0 sind, nicht geändert wird.

**Comment by foxthefox** [comment]
Wie gesagt, ich hatte etwas mit der Rundung angefangen. Schaue es mir heute an

**Comment by foxthefox** [comment]
ist mit der Version 0.2.1 behoben
