### ISSUE TITLE
Is it possible 2 tariff energy group?

### ISSUE THREAD

**Issue by itProfi** [foxthefox/ioBroker.statistics#23]
In Russia, for example, have 2 -4 tarif for energy. First tarif 07-00 - 23-00, second tarif 23-00 - 07-00 and 3 tarif - holidays..Is it possible create group with houres, for example?

**Comment by foxthefox** [comment]
Are there different energy meters for the different tariffs?

**Comment by itProfi** [comment]
No, only time is important. I use Tasmota:
![Скриншот 08-06-2019 213308](https://user-images.githubusercontent.com/6728198/59151036-38a8d800-8a35-11e9-9b71-356e14d225d1.jpg)
![Скриншот 08-06-2019 213310](https://user-images.githubusercontent.com/6728198/59151037-38a8d800-8a35-11e9-9091-efdfdf56c949.jpg)

**Comment by itProfi** [comment]
Any chance? :)

**Comment by foxthefox** [comment]
In principle everything could be programmed, but I am afraid that I have not the time to implement such a strategical change in the adapter in due time. It should be than universal enough to cope with different times and amount of tariffs.

**Comment by itProfi** [comment]
Unfortunately, I am new to js..((

**Comment by itProfi** [comment]
foxthefox, can you help, please..
