### ISSUE TITLE
Änderungen bei true / false werden nicht erkannt

### ISSUE THREAD

**Issue by mctom** [foxthefox/ioBroker.statistics#24]
Hi,

ich habe ein Objekt, dass ich mit statistics überwachen will. 
Leider werden die Änderungen nicht erkannt und deshalb gibt es auch keine Auswertungen.
Kann weitere Daten zur Analyse liefern ?

Gruß

MT

![2019-06-10 13_56_35-Window](https://user-images.githubusercontent.com/12543796/59193929-a36a2880-8b87-11e9-8216-9af69df5a9dd.png)
![2019-06-10 13_56_21-Window](https://user-images.githubusercontent.com/12543796/59193930-a36a2880-8b87-11e9-9a5c-2527b47427fb.png)
![2019-06-10 13_55_57-Window](https://user-images.githubusercontent.com/12543796/59193931-a36a2880-8b87-11e9-98f8-9164d71f5d8d.png)

**Comment by foxthefox** [comment]
Hi,
das Problem liegt in ack = false (erster screenshot).
wenn ack = false, dann handelt es sich um Kommandos und nicht um Rückmeldungen.
Statistiken werden nur von Rückmeldungen gebildet, d.h. ack = true.
Sofern es möglich ist, den setValue im javascript mit ack=true absetzen, dann sollte es auch mit dem Zählen klappen.

Gruß
Klaus

**Comment by mctom** [comment]
Danke für den Hinweis. Habe mein Script angepasst. Jetzt funktioniert es.
