### ISSUE TITLE
Error if state does not exist.

### ISSUE THREAD

**Issue by GermanBluefox** [foxthefox/ioBroker.statistics#33]
![Screenshot_20200103-144400_Telegram](https://user-images.githubusercontent.com/4582016/71726510-9cfb1100-2e37-11ea-9753-c48b2c0d95ed.jpg)

**Comment by GermanBluefox** [comment]
https://github.com/foxthefox/ioBroker.statistics/blob/master/main.js#L1191

**Comment by foxthefox** [comment]
state.lc should exist, or am I wrong?
is there something changed in the js-controller?
