### ISSUE TITLE
Update stable version in repo to 0.2.2

### ISSUE THREAD

**Issue by GermanBluefox** [foxthefox/ioBroker.statistics#39]
# Think about update stable version to 0.2.2
**Version**: stable=**0.2.0** (409 days old) => latest=**0.2.2** (248 days old)
**Installs**: stable=**839** (58.34%), latest=**572** (39.78%), total=**1438**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1261)

**Comment by foxthefox** [comment]
done with
ioBroker/ioBroker.repositories#659
