### ISSUE TITLE
AVG values are rounded to full integer

### ISSUE THREAD

**Issue by ratte-rizzo** [foxthefox/ioBroker.statistics#48]
Since some time (21 Mar 2020 in my case), the AVG values of temp and save are rounded to full integer. This was not the case in the past, where comma values were calculated

Delete and new install of adapter without success. 

![Screenshot_2020-06-01 objects - ioBroker](https://user-images.githubusercontent.com/45067101/83410514-cf289300-a416-11ea-98bf-6ea43ee079e6.png)
.

**Comment by J-Paul0815** [comment]
Same here, unfortunately useless. 
Two decimal places would be a minimum
