### ISSUE TITLE
Values stay in temp and never go to safe

### ISSUE THREAD

**Issue by Christin-Michelle** [foxthefox/ioBroker.statistics#56]
Might well be that I make a mistake but I have the adapter up and running and I do get values in the temp folder but none in the save folder... what can I do?

**Comment by foxthefox** [comment]
that seems strange and there is no adjustment necessary, this is done automatically

**Comment by Christin-Michelle** [comment]
I found a problem in the logs which might relate. When I started the adapter it said something like illegal time zone definition in the cron job definition. So it might be that it did not start the cron job. I revised the time zone setting to something cron understands and these errors are gone. I will probably see tomorrow or the day after if this solves the issue,

**Comment by foxthefox** [comment]
perfect, this was hopefully a message from statistics adapter.
I added this message in version 1.0.2.
And this is definitely the cause of the nightly turnover temp2save

**Comment by Christin-Michelle** [comment]
I waited two days now hoping that there would be a change for the better. Unfortunately it did not help any. I uninstalled to adapter now and reinstalled it. Now I left the field for the time zone empty hoping this will do any good.

**Comment by Christin-Michelle** [comment]
Hi

Nach einer Deinstallation und folgenden Neuinstallation läuft es jetzt und
die SAVE - Values werden upgedatet.

Leider habe ich keinen Plan woran es gelegen hat.

LG und Danke für den Support

Am Di., 19. Jan. 2021 um 07:41 Uhr schrieb foxthefox <
notifications@github.com>:
