### ISSUE TITLE
Travis testing is red ... Please fix after merging with Bluefox version!

### ISSUE THREAD

**Issue by Apollon77** [foxthefox/ioBroker.statistics#8]
e.g. https://travis-ci.org/Apollon77/ioBroker.statistics/jobs/459513313

**Comment by foxthefox** [comment]
if I have found out, what shall be the intention of the test, then I may have a glue.
It would have been perfect if, it would be already green from bluefox

**Comment by Apollon77** [comment]
The basic tests (as it exist e.g. in template adapter) mainly make sure that the adapter cna be installed and basically started. 
Here additional check logic was added : https://github.com/foxthefox/ioBroker.statistics/blob/master/test/testAdapter.js#L96 (and following) and https://github.com/foxthefox/ioBroker.statistics/blob/master/test/testAdapter.js#L123 ... so one object is added and an increasing counter value is written into it each second.

Then after everything started up in https://github.com/foxthefox/ioBroker.statistics/blob/master/test/testAdapter.js#L153 it is checked that adapter has created two own objects and it is checked that they exist.

I think the main topic is that the counter gets increased all the time ... there is no stop. SO in my eyes there should be a clearInterval once the check was done. This should be enough already

**Comment by Apollon77** [comment]
testing still red

**Comment by foxthefox** [comment]
I am still struggling with it. I found one issue in travis log "cannot find view "custom"", but I have no glue how to solve it.

**Comment by foxthefox** [comment]
now it is green

**Comment by Apollon77** [comment]
Cool what was it?

**Comment by Apollon77** [comment]
Congrats!
